### ISSUE TITLE
Decide on article selection method

### ISSUE THREAD

**Issue by zachary-foster** [phytopathology/Reproducible.Plant.Pathology#6] opened 2017-03-23 17:59 UTC
I like what @adamhsparks did  [here](https://github.com/adamhsparks/Reproducible-Research-in-Plant-Pathology/tree/master/src). Any other ideas?

**Comment by adamhsparks** [comment] 2017-04-04 04:28
Since no one else has suggested otherwise, let's use my method and adjust the numbers as necessary.

**Comment by grunwald** [comment] 2017-04-04 14:45
I suggest excluding review articles. Selecting plant pathology articles and randomly selecting 20 papers each by a few tiers of IF might work? 

IF tiers:
- 0-1
- 1-2
- 2-3
- 3-5
- > 5

**Comment by adamhsparks** [comment] 2017-04-04 20:35
I think that selecting based on IF might leave us with alot more in some than others. 

This is spilling over a bit from #3. The intent of this issue was to determine the actual mechanism we used, I've written an Rmd file that illustrates random sampling of articles. It's not perfect, we'll end up with reviews (I agree with excluding review articles) and some that aren't plant pathology from _Crop Protection_ and the like, but we can always just resample to fill in those gaps.

**Comment by adamhsparks** [comment] 2017-04-10 06:44
I've updated our journal sampling methods to include 200 articles from the 20 journals that @emdelponte suggested.

I've assigned each of us to 50 random articles and sorted the list of articles by our names.

https://github.com/adamhsparks/Reproducible-Research-in-Plant-Pathology/tree/master/src

@emdelponte, are all articles in Revista Mexicana de Fitopatología fully bilingual?

**Comment by grunwald** [comment] 2017-04-10 14:14
@adamhsparks, thanks for getting articles assigned to us! Time to get to work ... Can we get the doi for each article assigned to us?

**Comment by emdelponte** [comment] 2017-04-10 14:29
@adamhsparks yes, looks like all of them are in both languages, side by side! at least from 2012 which are freely available at their website. 

If I understood correctly, we should pick the article for which the page interval contains the randomly selected page, correct? For example, for this one on Revista Mexicana de Fitopatologia assigned to me (2014, 98) the page interval was 89 to 107. However, this is a review article (http://rmf.smf.org.mx/Vol3222014/AR/32-2_02.pdf). In this case, should we pick the following article in the same issue?

**Comment by adamhsparks** [comment] 2017-04-10 20:22
@grunwald, I'll see what I can do to get DOIs for everyone and put them in the same markdown file.

@emdelponte, yes, I think that's the best strategy for reviews or other that might not apply, take the next one in the issue. If it's the last one, then take the one before. Just document what was done.

**Comment by adamhsparks** [comment] 2017-04-23 23:25
See [Article selection method and evaluator assignments](https://github.com/phytopathology/Reproducible.Plant.Pathology/blob/master/vignettes/Assigning_Articles.Rmd)

**Closed by adamhsparks** 2017-04-23 23:25 UTC
